name: zebra_barcode_reader
description: Flutter plugin for reading barcodes.
repository: https://github.com/suatkeskin/zebra_barcode_reader/tree/main/zebra_barcode_reader
issue_tracker: https://github.com/suatkeskin/zebra_barcode_reader/issues
version: 1.0.3

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

flutter:
  plugin:
    platforms:
      android:
        default_package: zebra_barcode_reader_android

dependencies:
  flutter:
    sdk: flutter
  zebra_barcode_reader_android: ^1.0.4
  zebra_barcode_reader_platform_interface: ^1.0.5

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

topics:
  - zebra
  - barcode
  - mc3300x
