name: zebra_barcode_reader_android_example
description: "Demonstrates how to use the zebra_barcode_reader_android plugin."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  zebra_barcode_reader_android:
    path: ../
  zebra_barcode_reader_platform_interface: ^1.0.5
  stream_transform: ^2.1.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
